Name: Ramya R
Reg No: 212223230169

In [5]:
import numpy as np

Question 1 – Student Marks Array
The marks obtained by five students in a subject are given as [78, 65, 89, 56, 92]. Create a NumPy array and display the array along with its basic properties.

In [6]:

marks = np.array([78, 65, 89, 56, 92])

print("Marks:", marks)
print("Number of dimensions:", marks.ndim)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data type:", marks.dtype)

Marks: [78 65 89 56 92]
Number of dimensions: 1
Shape: (5,)
Size: 5
Data type: int32


Question 2 – Student Marks Access
The marks of five students are stored in a NumPy array as [72, 85, 64, 90, 76]. Write a program to access and display specific student marks using NumPy indexing and slicing.

In [8]:
marks = np.array([72, 85, 64, 90, 76])

print("Marks:", marks)

print("First student:", marks[0])
print("Third student:", marks[2])
print("Last student:", marks[-1])

print("First three students:", marks[:3])
print("Second to fourth:", marks[1:4])
print("Last two students:", marks[-2:])

Marks: [72 85 64 90 76]
First student: 72
Third student: 64
Last student: 76
First three students: [72 85 64]
Second to fourth: [85 64 90]
Last two students: [90 76]


Question 3 – Subject-wise Marks
The marks obtained by five students in three subjects are given below. Create a NumPy array to represent the data and reshape it into an appropriate matrix format.
[78, 85, 90, 65, 72, 80, 88, 91, 84, 56, 62, 70, 95, 89, 92]


In [9]:
marks = np.array([
    78, 85, 90,
    65, 72, 80,
    88, 91, 84,
    56, 62, 70,
    95, 89, 92
])

matrix = marks.reshape(5, 3)

print("Original array:")
print(marks)

print("\nMarks Matrix:")
print(matrix)

Original array:
[78 85 90 65 72 80 88 91 84 56 62 70 95 89 92]

Marks Matrix:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


Question 4 – Internal and External Marks
The internal and external examination marks of five students are stored in two NumPy arrays. Write a program to calculate the final marks of each student using NumPy array operations.


In [25]:
internal = np.array([20, 18, 22, 19, 21])
external = np.array([70, 65, 68, 72, 75])

final_marks = internal + external

print("Internal Marks:", internal)
print("External Marks:", external)
print("Final Marks:", final_marks)

Internal Marks: [20 18 22 19 21]
External Marks: [70 65 68 72 75]
Final Marks: [90 83 90 91 96]


Question 5 – Pass Percentage Analysis
The marks obtained by five students are [45, 78, 56, 32, 91]. Using NumPy Boolean masking, identify the students who have secured 50 marks or above.


In [23]:
marks = np.array([45, 78, 56, 32, 91])

passed = marks >= 50

print("Marks:", marks)
print("Pass condition:", passed)
print("Students scoring 50 or above:", marks[passed])

Marks: [45 78 56 32 91]
Pass condition: [False  True  True False  True]
Students scoring 50 or above: [78 56 91]


Question 6 – Average Marks
The marks of five students in three subjects are represented using a NumPy matrix. Write a program to calculate the average marks of each student.


In [22]:
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

average = np.mean(marks, axis=1)

print("Marks:")
print(marks)

print("\nAverage marks of each student:")
print(average)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Average marks of each student:
[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


Question 7 – Class Performance Statistics
The marks obtained by five students are [67, 82, 91, 74, 58]. Using NumPy statistical functions, determine the total, average, highest, lowest, and standard deviation of the marks.


In [21]:
marks = np.array([67, 82, 91, 74, 58])

print("Marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard Deviation:", np.std(marks))

Marks: [67 82 91 74 58]
Total: 372
Average: 74.4
Highest: 91
Lowest: 58
Standard Deviation: 11.46472851837321


Question 8 – Subject-wise Performance
The marks of five students in three subjects are stored in a NumPy matrix. Write a program to calculate the total marks obtained in each subject using an appropriate axis operation.


In [20]:
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

subject_total = np.sum(marks, axis=0)

print("Marks:")
print(marks)

print("\nTotal marks in each subject:")
print(subject_total)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Total marks in each subject:
[382 399 416]


Question 9 – Student-wise Performance
The marks of five students in three subjects are stored in a NumPy matrix. Write a program to calculate the total marks obtained by each student using an appropriate axis operation.


In [19]:
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

student_total = np.sum(marks, axis=1)

print("Marks:")
print(marks)

print("\nTotal marks of each student:")
print(student_total)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Total marks of each student:
[253 217 263 188 276]


Question 10 – Student Ranking
The total marks obtained by five students are [245, 278, 219, 290, 256]. Use NumPy sorting and indexing operations to arrange the marks in order and determine the ranking of the students.


In [18]:
marks = np.array([245, 278, 219, 290, 256])

sorted_marks = np.sort(marks)[::-1]

ranking = np.argsort(marks)[::-1]

print("Original marks:", marks)

print("Marks in descending order:", sorted_marks)

print("\nRanking:")
for rank, index in enumerate(ranking, start=1):
    print("Rank", rank, "- Student", index + 1,
          "- Marks:", marks[index])

Original marks: [245 278 219 290 256]
Marks in descending order: [290 278 256 245 219]

Ranking:
Rank 1 - Student 4 - Marks: 290
Rank 2 - Student 2 - Marks: 278
Rank 3 - Student 5 - Marks: 256
Rank 4 - Student 1 - Marks: 245
Rank 5 - Student 3 - Marks: 219


Question 11 – Duplicate Marks Analysis
The marks obtained by five students are [85, 92, 85, 76, 92]. Use NumPy functions to identify the unique marks obtained by the students.


In [17]:
marks = np.array([85, 92, 85, 76, 92])

unique_marks = np.unique(marks)

print("Marks:", marks)
print("Unique marks:", unique_marks)

Marks: [85 92 85 76 92]
Unique marks: [76 85 92]


Question 12 – Missing Marks
The marks of five students are represented as [78, 85, np.nan, 92, 67], where np.nan represents a missing mark. Write a NumPy program to calculate the average marks without considering the missing value.

In [16]:
marks = np.array([78, 85, np.nan, 92, 67])

average = np.nanmean(marks)

print("Marks:", marks)
print("Average excluding missing value:", average)

Marks: [78. 85. nan 92. 67.]
Average excluding missing value: 80.5


Question 13 – Grade Classification
The marks obtained by five students are [95, 82, 74, 61, 45]. Using NumPy conditional operations, classify the students into appropriate grade categories based on their marks.

In [14]:
marks = np.array([95, 82, 74, 61, 45])

grades = np.select(
    [
        marks >= 90,
        marks >= 80,
        marks >= 70,
        marks >= 60
    ],
    [
        "A",
        "B",
        "C",
        "D"
    ],
    default="F"
)

print("Marks:", marks)
print("Grades:", grades)

Marks: [95 82 74 61 45]
Grades: ['A' 'B' 'C' 'D' 'F']


Question 14 – Random Marks Generation
Generate marks for five students using NumPy's random number generation functionality. Perform basic statistical analysis on the generated marks.


In [13]:
marks = np.random.randint(0, 101, size=5)

print("Generated marks:", marks)

print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard deviation:", np.std(marks))

Generated marks: [29 89 71 78 93]
Total: 360
Average: 72.0
Highest: 93
Lowest: 29
Standard deviation: 22.873565528793275


Question 15 – Student Performance Analysis
The marks of five students in three subjects are stored in a NumPy array. Develop a program to perform a complete student performance analysis by calculating the total marks, average marks, highest marks, lowest marks, and identifying students who perform above the class average.


In [12]:
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

# Total marks of each student
total = np.sum(marks, axis=1)

# Average marks of each student
average = np.mean(marks, axis=1)

# Highest mark of each student
highest = np.max(marks, axis=1)

# Lowest mark of each student
lowest = np.min(marks, axis=1)

# Class average
class_average = np.mean(marks)

# Students above class average
above_average = np.where(average > class_average)[0]

print("Marks:")
print(marks)

print("\nTotal marks:", total)
print("Average marks:", average)
print("Highest marks:", highest)
print("Lowest marks:", lowest)

print("\nClass average:", class_average)

print("\nStudents above class average:")
for index in above_average:
    print("Student", index + 1)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Total marks: [253 217 263 188 276]
Average marks: [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]
Highest marks: [90 80 91 70 95]
Lowest marks: [78 65 84 56 89]

Class average: 79.8

Students above class average:
Student 1
Student 3
Student 5
